# Generated by Django 4.0.3 on 2022-04-14 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='imgs/media')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_list', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('reply_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tweets.status')),
                ('retweet_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='tweets.status')),
            ],
        ),
    ]
